# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterLogEntry',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.LogEntry')),
                ('_type', models.CharField(choices=[('t', 'Tweet'), ('i', 'Incoming Direct Message'), ('o', 'Outcoming Direct Message')], max_length=1)),
                ('text', models.TextField(help_text='Full text context. Usually 140 characters tops.', verbose_name='text')),
                ('datetime', models.DateTimeField(help_text='Date and time the object was sent or received.', verbose_name='date and time')),
            ],
            options={
                'verbose_name_plural': 'Twitter objects',
                'verbose_name': 'Twitter object',
            },
            bases=('base.logentry',),
        ),
        migrations.CreateModel(
            name='TwitterSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Source')),
            ],
            options={
                'verbose_name_plural': 'Connections to Twitter',
                'verbose_name': 'Twitter',
            },
            bases=('base.source',),
        ),
    ]
