# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterlogentry',
            name='external_id',
            field=models.BigIntegerField(default=0, verbose_name='Object ID on Twitter'),
            preserve_default=False,
        ),
    ]
