# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_owned_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSEntry',
            fields=[
                ('logentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.LogEntry')),
                ('type', models.CharField(choices=[('i', 'Incoming'), ('o', 'Outcoming')], max_length=1)),
                ('text', models.TextField(help_text="The SMS' full text.", verbose_name='SMS text')),
                ('received', models.BooleanField(help_text='A flag indicating whether an outcoming SMS was received.', verbose_name='received')),
                ('datetime', models.DateTimeField(help_text='Date and time the SMS was sent/received.', verbose_name='date and time')),
                ('contact_phone', models.ForeignKey(help_text='The phone number related to the contact.', on_delete=django.db.models.deletion.CASCADE, to='base.ContactPhone', verbose_name='contact phone')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.logentry',),
        ),
    ]
