# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('msisdn', models.CharField(max_length=15)),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contact')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contactphone',
            unique_together=set([('contact', 'msisdn')]),
        ),
    ]
