# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 04:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactphone',
            name='msisdn',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
