# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 05:23
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_owned_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactphone',
            options={'verbose_name': 'contact phone', 'verbose_name_plural': 'contact phones'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='The name of the contact. Try to avoid repeatable names.', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('p', 'Person'), ('t', 'Thing')], help_text='The type of contact; either a person or a thing (e.g. company).', max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='update timestamp'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='base_contact_set', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='contact',
            field=models.ForeignKey(help_text='The contact that owns this phone number.', on_delete=django.db.models.deletion.CASCADE, to='base.Contact', verbose_name='phone owner'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='label',
            field=models.CharField(blank=True, help_text='An optional label to represent this phone number.', max_length=20, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='msisdn',
            field=models.CharField(help_text='The phone number, including country code. Digits only.', max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='MSISDN (number)'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='update timestamp'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='base_contactphone_set', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='contact',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Contact', verbose_name='related contact'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='update timestamp'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='base_logentry_set', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
