# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='source',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Source', verbose_name='related source'),
        ),
    ]
